{% set name = "metocean-api" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c9add18b589de5e55541ab953d7be3bbd6111357469f57145947a8e533d7191

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools-scm
  run:
    - python =>3.9
    - matplotlib-base >=3.1
    - numpy >=1.17
    - pandas
    - xarray
    - dask
    - pynco
    - netcdf4
    - pytest
    - cdsapi

test:
  imports:
    - metocean_api
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MET-OM/metocean-api
  summary: 'Package to extract time series of metocean data from global/regional/coastal hindcast'
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  doc_url: https://metocean-api.readthedocs.io/
  dev_url: https://github.com/MET-OM/metocean-api

extra:
  recipe-maintainers:
    - KonstantinChri
