{% set name = "metocean-api" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dede230775550ee5a3e7d07f774be77facbbbcac879c812a57d36924570c15dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python 3.9
    - pip
    - setuptools
  run:
    - python 3.9
    - matplotlib-base >=3.1
    - numpy >=1.17
    - pandas
    - xarray
    - dask >=2024.9.1
    - netcdf4
    - pytest
    - pytest-cov
    - cdsapi
    - cartopy

test:
  imports:
    - metocean_api
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MET-OM/metocean-api
  summary: 'Package to extract time series of metocean data from global/regional/coastal hindcast'
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE.txt
  doc_url: https://metocean-api.readthedocs.io/
  dev_url: https://github.com/MET-OM/metocean-api

extra:
  recipe-maintainers:
    - KonstantinChri
