{% set name = "metocean-api" %}
{% set version = "1.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9d7c89ac8d3495e94d7b4b9420cb1fb321e8c1dda11daa3c7e6165d110f7760e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python {{ python_min }}
    - matplotlib-base >=3.1
    - numpy >=1.17
    - pandas
    - xarray
    - dask >=2024.9.1
    - netcdf4
    - pytest
    - pytest-cov
    - cdsapi
    - cartopy

test:
  imports:
    - metocean_api
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/MET-OM/metocean-api
  summary: 'Package to extract time series of metocean data from global/regional/coastal hindcast'
  license: LGPL-2.0-only
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://metocean-api.readthedocs.io/
  dev_url: https://github.com/MET-OM/metocean-api

extra:
  recipe-maintainers:
    - KonstantinChri
